### ISSUE TITLE
Why just work with BMP3?

### ISSUE THREAD

**Issue by QuestionPython** [karthikb351/CaptchaParser#7]
hi
i think this just work with `BMP3`, and not work with `BMP55` and `JPG`......

how can convert a `.JPG` to `BMP3`?

i want try with image : http://itadoor.com/captcha.jpg

**Comment by questionpython** [comment]
!

**Comment by karthikb351** [comment]
This algorithm just needs a pixel map (a 2D matrix of pixel values) to work. You should be able to find a library that can let you generate that from JPGs.

**Comment by questionpython** [comment]
so how can convert image(http://itadoor.com/captcha.jpg) to a 2D matrix image?

**Comment by questionpython** [comment]
!?

**Comment by questionpython** [comment]
!

**Comment by karthikb351** [comment]
One method is to use a HTML canvas and address each pixel in a nested for loop and build the map.
As mentioned here: [http://stackoverflow.com/questions/8751020/how-to-get-a-pixels-x-y-coordinate-color-from-an-image](http://stackoverflow.com/questions/8751020/how-to-get-a-pixels-x-y-coordinate-color-from-an-image)
