### ISSUE TITLE
Reduce run time of the code

### ISSUE THREAD

**Issue by Presto412** [karthikb351/CaptchaParser#8]
I've made a few changes to the python script, and the run time has been reduced to an average of 0.13 seconds, almost half of the earlier. Is it okay if I put up a pull request?

**Comment by karthikb351** [comment]
Please do!

**Comment by Presto412** [comment]
I'll do it by tomorrow. Also, I have used your base character matrices and my own algorithm whose runtime is about 1.3 seconds, could you help me optimise it? Check the VIT-CaptchaParser repo in my profile.
Thanks!

**Comment by karthikb351** [comment]
Closed via #9
